default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [ "--no-update" ]
#      - id: poetry-export
#        args: [ "-o", "requirements.txt", "--with", "dev", "--with", "docs", "--without-hashes" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: fix-encoding-pragma
#      - id: trailing-whitespace
#        args: [--markdown-linebreak-ext=md]
#      - id: check-symlinks
#      - id: destroyed-symlinks
#      - id: end-of-file-fixer
#      - id: pretty-format-json
#        args: [ --autofix ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
      - id: mypy
        additional_dependencies: [
          pydantic,
          types-pytz,
          types-requests,
          types-setuptools,
          types-tzlocal
        ]
